server.port: 8080
author:
  name: saber
  baiduurl: https://baidu.com

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: html5
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.example.springboot.entity

#showsql
logging:
  level:
    com:
      example:
        mapper: debug
